# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06bb376f9596b888891f2af4ae6fed65bb75c0b4c771d722063e678314b7f35c24519490feef3bdb1a807b07a90b6c735c2673e98139e2a6dc35c9ab9369ad9c

test:
  secret_key_base: c4ba595c0dc9dfe67cab951143cac661658292369078a1b341a3fe3e1a6ce64ce67c2770d6a54e04f383983c580ecf14d17a692ec4f5358836ab052851f116d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
